# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CPF', models.CharField(max_length=14)),
                ('Nome', models.CharField(max_length=30)),
                ('Endereco', models.CharField(max_length=35)),
                ('Complemento', models.CharField(max_length=50)),
                ('Cidade', models.CharField(max_length=25)),
                ('Estado', models.CharField(max_length=2)),
                ('CEP', models.CharField(max_length=8)),
                ('FoneResidencial', models.CharField(max_length=15)),
                ('FoneTrabalho', models.CharField(max_length=15)),
                ('RendaFamiliar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
