# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CNPJ', models.CharField(max_length=20)),
                ('Nome', models.CharField(max_length=30)),
                ('Endereco', models.CharField(max_length=35)),
                ('Complemento', models.CharField(max_length=50)),
                ('Cidade', models.CharField(max_length=25)),
                ('Estado', models.CharField(max_length=2)),
                ('CEP', models.CharField(max_length=8)),
                ('Fone', models.CharField(max_length=15)),
                ('Responsavel', models.CharField(max_length=30)),
                ('Wrbsite', models.CharField(max_length=80)),
            ],
        ),
    ]
