# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_fornecedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PrecoUnitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Quantidade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PrecoUnitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Quantidade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DataPedido', models.DateField()),
                ('DataRecebimento', models.DateField()),
                ('PrecoTotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('CodigoFornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomeProduto', models.CharField(max_length=35)),
                ('Quantidade', models.IntegerField()),
                ('MinQuantidade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DataVenda', models.DateTimeField()),
                ('ValorTotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cliente')),
            ],
        ),
        migrations.AddField(
            model_name='itemvenda',
            name='CodigoProduto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Produto'),
        ),
        migrations.AddField(
            model_name='itemvenda',
            name='CodigoVenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Venda'),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='CodigoPedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Pedido'),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='CodigoProduto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Produto'),
        ),
    ]
