# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-19 05:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170418_1444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venda',
            old_name='Cliente',
            new_name='ClienteVenda',
        ),
    ]
